openapi: 3.0.1
info:
  contact:
    name: Polarion REST API Support
    url: https://support.sw.siemens.com/
  description: <h5>About</h5>The Polarion REST API lets you interact with Polarion programmatically. Use this API to integrate Polarion with your applications. This page documents the REST resources, including the HTTP response codes and example requests and responses. <br/><br/>For a detailed description of the REST API and how to use it, see the <a href="https://docs.sw.siemens.com/en-US/doc/230235217/PL20250606201928474.polarion_help_sc.xid2134849/xid2134871" target="_blank">REST API User Guide</a> (available on Support Center).
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: Polarion REST Account Profitability Calculation API
  version: v1
servers:
- url: https://example.com/polarion/rest/v1
security:
- bearerAuth: []
tags:
- name: Profitability Calculation
paths:
  /api/v1/profitability-calculation-report:
    get:
      summary: Returns the profitability calculation report. Available since version 2406.0001
      security:
      - bearerHttpAuthentication: []
      responses:
        '200':
          headers: {}
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/DataSet'
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProfitabilityCalculationReportError'
                required:
                - data
              examples:
                Example:
                  value:
                    data:
                      data:
                      - Name: Profitability Calculation for car A
                        Year: 2025
                        Revenue: 2346825
                      - Name: Profitability Calculation for car A
                        Year: 2026
                        Revenue: 4341822
                      columns:
                      - name: Name
                        displayName: Profitability Calculation Name
                        dataType: string
                      - name: Year
                        displayName: Year
                        dataType: integer
                      - name: Revenue
                        displayName: Revenue in €
                        dataType: double
                    errors:
                    - status: 404
                      detail: Profitability calculation not found
                      profitabilityCalculationId: 731
            application/xml:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/DataSet'
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/ProfitabilityCalculationReportError'
                required:
                - data
          description: Success. Returns the requested profitability calculation report.
        '400':
          $ref: '#/components/responses/ErrorBadRequestLegacy'
        '401':
          $ref: '#/components/responses/ErrorUnauthorizedLegacy'
        '406':
          $ref: '#/components/responses/ErrorNotAcceptableLegacy'
        '408':
          $ref: '#/components/responses/ErrorRequestTimeoutLegacy'
        '500':
          $ref: '#/components/responses/ErrorInternalServerErrorLegacy'
      operationId: get-ProfitabilityCalculation
      description: Returns the profitability calculation report. Available since version 2406.0001.
      parameters:
      - $ref: '#/components/parameters/ProfitabilityCalculationIds'
      - $ref: '#/components/parameters/ProjectIds'
      - $ref: '#/components/parameters/ExportConfigurationGuid'
      tags:
      - Profitability Calculation
  /api/v1/aggregated-profitability-calculation-report:
    get:
      summary: Returns the aggregated profitability calculation report. Available since version 2512.2602
      security:
      - bearerHttpAuthentication: []
      responses:
        '200':
          headers: {}
          description: Success. Returns the requested aggregated profitability calculation report.
          content:
            application/json:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/DataSet'
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/AggregatedProfitabilityCalculationReportError'
                required:
                - data
              examples:
                Example:
                  value:
                    data:
                      data:
                      - Name: Aggregated Profitability Calculation for plant Munich
                        Year: 2025
                        Revenue: 2346825
                      - Name: Aggregated Profitability Calculation for plant Munich
                        Year: 2026
                        Revenue: 4341822
                      columns:
                      - name: Name
                        displayName: Aggregated Profitability Calculation Name
                        dataType: string
                      - name: Year
                        displayName: Year
                        dataType: integer
                      - name: Revenue
                        displayName: Revenue in €
                        dataType: double
                    errors:
                    - status: 404
                      detail: Aggregated profitability calculation not found
                      aggregatedProfitabilityCalculationId: 731
            application/xml:
              schema:
                type: object
                properties:
                  data:
                    $ref: '#/components/schemas/DataSet'
                  errors:
                    type: array
                    items:
                      $ref: '#/components/schemas/AggregatedProfitabilityCalculationReportError'
                required:
                - data
        '400':
          $ref: '#/components/responses/ErrorBadRequest'
        '401':
          $ref: '#/components/responses/ErrorUnauthorized'
        '406':
          $ref: '#/components/responses/ErrorNotAcceptable'
        '408':
          $ref: '#/components/responses/ErrorRequestTimeout'
        '500':
          $ref: '#/components/responses/ErrorInternalServerError'
      operationId: get-AggregatedProfitabilityCalculationReport
      description: Returns the aggregated profitability calculation report. Available since version 2512.2602.
      parameters:
      - in: query
        name: AggregatedProfitabilityCalculationIds
        description: Ids of the aggregated profitability calculations to be exported.
        schema:
          type: array
          items:
            type: integer
        example:
        - 14
        - 362
        - 731
      - in: query
        name: FolderIds
        description: All aggregated profitability calculations of these folders are exported.
        schema:
          type: array
          items:
            type: integer
        example:
        - 5
        - 12
      - $ref: '#/components/parameters/ExportConfigurationGuid'
      tags:
      - Profitability Calculation
components:
  responses:
    ErrorInternalServerError:
      description: An unexpected error occurred and the server is not fulfilling the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Example:
              value:
                errors:
                - detail: Internal error
        application/xml:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ErrorNotAcceptableLegacy:
      description: The service is not able to respond using the request media-type or representation asked by the client in the Accept header.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorLegacy'
          examples:
            Example:
              value:
                Detail: Media type not accepted
        application/xml:
          schema:
            $ref: '#/components/schemas/ErrorLegacy'
    ErrorUnauthorizedLegacy:
      description: The client is not providing valid authentication credentials for the target resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorLegacy'
          examples:
            Example:
              value:
                Detail: Invalid user or password
        application/xml:
          schema:
            $ref: '#/components/schemas/ErrorLegacy'
    ErrorRequestTimeoutLegacy:
      description: The request timed out because a server did not respond within the expected waiting time
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorLegacy'
          examples:
            Example:
              value:
                Detail: Request timed out
        application/xml:
          schema:
            $ref: '#/components/schemas/ErrorLegacy'
    ErrorInternalServerErrorLegacy:
      description: An unexpected error occurred and the server is not fulfilling the request.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorLegacy'
          examples:
            Example:
              value:
                Detail: Internal error
        application/xml:
          schema:
            $ref: '#/components/schemas/ErrorLegacy'
    ErrorBadRequestLegacy:
      description: The request could not be processed by the server because the request is perceived as client error (such as, malformed request syntax, invalid request message framing, or deceptive request routing).
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorLegacy'
          examples:
            Example:
              value:
                Detail: Invalid JSON format
        application/xml:
          schema:
            $ref: '#/components/schemas/ErrorLegacy'
    ErrorUnauthorized:
      description: The client is not providing valid authentication credentials for the target resource.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Example:
              value:
                errors:
                - detail: Invalid user or password
        application/xml:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ErrorBadRequest:
      description: The request could not be processed by the server because the request is perceived as client error (such as, malformed request syntax, invalid request message framing, or deceptive request routing).
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Example:
              value:
                errors:
                - detail: Invalid JSON format
        application/xml:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ErrorRequestTimeout:
      description: The request timed out because a server did not respond within the expected waiting time
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Example:
              value:
                errors:
                - detail: Request timed out
        application/xml:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
    ErrorNotAcceptable:
      description: The service is not able to respond using the request media-type or representation asked by the client in the Accept header.
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
          examples:
            Example:
              value:
                errors:
                - detail: Media type not accepted
        application/xml:
          schema:
            $ref: '#/components/schemas/ErrorResponse'
  schemas:
    ProfitabilityCalculationReportError:
      title: ProfitabilityCalculationReportError
      type: object
      description: Partial error of a profitability calculation report request.
      required:
      - status
      - detail
      properties:
        status:
          type: integer
          format: int32
          minimum: 0
          description: Http status code
          readOnly: true
        detail:
          type: string
          description: Detail description of the error
        profitabilityCalculationId:
          type: integer
          format: int32
          minimum: 0
          description: Id of the requested profitability calculation
          readOnly: true
        projectId:
          type: integer
          format: int32
          minimum: 0
          description: Id of the requested project
          readOnly: true
    DataType:
      type: string
      enum:
      - double
      - integer
      - date
      - string
      - object
      - reference
      - bool
      - url
      example: double
    Column:
      title: Column
      type: object
      required:
      - dataType
      properties:
        name:
          type: string
          maxLength: 255
          minLength: 0
          description: Name of the data field
        displayName:
          type: string
          maxLength: 255
          minLength: 0
          description: Displayname of the column
        dataType:
          $ref: '#/components/schemas/DataType'
    Error:
      type: object
      properties:
        detail:
          type: string
          readOnly: true
    AggregatedProfitabilityCalculationReportError:
      title: ProfitabilityCalculationReportError
      type: object
      description: Partial error of an aggregated profitability calculation report request.
      required:
      - status
      - detail
      properties:
        status:
          type: integer
          format: int32
          minimum: 0
          description: Http status code
          readOnly: true
        detail:
          type: string
          description: Detail description of the error
        aggregatedProfitabilityCalculationId:
          type: integer
          format: int32
          minimum: 0
          description: Id of the requested aggregated profitability calculation
          readOnly: true
        folderId:
          type: integer
          format: int32
          minimum: 0
          description: Id of the requested folder
          readOnly: true
    DataSet:
      title: DataSet
      type: object
      description: Represents a two-dimensional data set with column descriptions including column data types.
      required:
      - data
      - columns
      properties:
        data:
          type: array
          description: Array of objects defining a two-dimensional array via the property names of the objects. See the 'columns' field for the display names and data types.
          maxItems: 100000
          items:
            type: object
        columns:
          type: array
          description: Columns of the dataset describing the names and the datatypes
          maxItems: 100000
          items:
            $ref: '#/components/schemas/Column'
    ErrorResponse:
      type: object
      properties:
        Errors:
          type: array
          items:
            $ref: '#/components/schemas/Error'
          readOnly: true
    ErrorLegacy:
      type: object
      properties:
        Detail:
          type: string
          readOnly: true
  parameters:
    ExportConfigurationGuid:
      name: ExportConfigurationGuid
      in: query
      required: true
      schema:
        type: string
        format: uuid
        example: cbbb4ada-3550-4939-a138-4da02757d460
      description: GUID of the export configuration.
    ProjectIds:
      name: ProjectIds
      in: query
      required: false
      schema:
        type: array
        items:
          type: integer
          format: int32
          minimum: 0
          maximum: 2147483647
      description: All profitability calculations of these projects are exported.
      example:
      - 53
      - 88
    ProfitabilityCalculationIds:
      name: ProfitabilityCalculationIds
      in: query
      required: false
      schema:
        type: array
        items:
          type: integer
          format: int32
          minimum: 0
          maximum: 2147483647
      description: Ids of the profitability calculations to be exported.
      example:
      - 3
      - 17
      - 732
  securitySchemes:
    bearerAuth:
      bearerFormat: JWT
      scheme: bearer
      type: http
