openapi: 3.2.0
info:
  version: v1.5
  title: TcPCM Gateway Basic API
  description: TcPCM Gateway API
  license:
    name: Privacy Policy
    url: https://www.plm.automation.siemens.com/global/en/legal/privacy-policy.html
tags:
- name: Basic
paths:
  /api/v1/masterData/ping:
    get:
      tags:
      - Basic
      operationId: MasterData_Ping
      summary: Check if the service is running
      responses:
        '200':
          description: Ok.
        '500':
          description: Indicates that a generic error has occurred on the server.
      deprecated: false
components:
  securitySchemes:
    bearerHttpAuthentication:
      type: http
      scheme: bearer
      bearerFormat: JWT
